/*
 * Somfy Protect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiException {
    /// Exception message.
    #[serde(rename = "message")]
    pub message: String,
    /// Exception data.
    #[serde(rename = "data")]
    pub data: Vec<String>,
    /// Exception UID.
    #[serde(rename = "uid")]
    pub uid: String,
}

impl ApiException {
    pub fn new(message: String, data: Vec<String>, uid: String) -> ApiException {
        ApiException { message, data, uid }
    }
}
