/*
 * Somfy Protect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DeviceSettingsPartial {
    /// Enable auto protection (for siren).
    #[serde(rename = "auto_protect_enabled", skip_serializing_if = "Option::is_none")]
    pub auto_protect_enabled: Option<bool>,
}

impl DeviceSettingsPartial {
    pub fn new() -> DeviceSettingsPartial {
        DeviceSettingsPartial {
            auto_protect_enabled: None,
        }
    }
}


