/*
 * Somfy Protect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DeviceCollection {
    /// List of devices.
    #[serde(rename = "items")]
    pub items: Vec<crate::models::DeviceOutput>,
}

impl DeviceCollection {
    pub fn new(items: Vec<crate::models::DeviceOutput>) -> DeviceCollection {
        DeviceCollection {
            items,
        }
    }
}


