/*
 * Somfy Protect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeviceSettings {
    #[serde(rename = "global")]
    pub global: Box<models::DeviceSettingsGlobal>,
    #[serde(rename = "disarmed", skip_serializing_if = "Option::is_none")]
    pub disarmed: Option<Box<models::DeviceSettingsDisarmed>>,
    #[serde(rename = "partial", skip_serializing_if = "Option::is_none")]
    pub partial: Option<Box<models::DeviceSettingsPartial>>,
    #[serde(rename = "armed", skip_serializing_if = "Option::is_none")]
    pub armed: Option<Box<models::DeviceSettingsArmed>>,
}

impl DeviceSettings {
    pub fn new(global: models::DeviceSettingsGlobal) -> DeviceSettings {
        DeviceSettings {
            global: Box::new(global),
            disarmed: None,
            partial: None,
            armed: None,
        }
    }
}
