/*
 * Somfy Protect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeviceCollection {
    /// List of devices.
    #[serde(rename = "items")]
    pub items: Vec<models::DeviceOutput>,
}

impl DeviceCollection {
    pub fn new(items: Vec<models::DeviceOutput>) -> DeviceCollection {
        DeviceCollection { items }
    }
}
