/*
 * Somfy Protect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeviceSettingsDisarmed {
    /// Enable auto protection (for siren).
    #[serde(
        rename = "auto_protect_enabled",
        skip_serializing_if = "Option::is_none"
    )]
    pub auto_protect_enabled: Option<bool>,
}

impl DeviceSettingsDisarmed {
    pub fn new() -> DeviceSettingsDisarmed {
        DeviceSettingsDisarmed {
            auto_protect_enabled: None,
        }
    }
}
