/*
 * Somfy Protect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Diagnosis {
    /// Is everything ok ?
    #[serde(rename = "is_everything_ok", skip_serializing_if = "Option::is_none")]
    pub is_everything_ok: Option<bool>,
    /// List of problems.
    #[serde(rename = "problems", skip_serializing_if = "Option::is_none")]
    pub problems: Option<Vec<String>>,
}

impl Diagnosis {
    pub fn new() -> Diagnosis {
        Diagnosis {
            is_everything_ok: None,
            problems: None,
        }
    }
}
