/*
 * Somfy Protect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DomesticAlarmOutputCollection {
    /// List of domestic alarms outpub.
    #[serde(rename = "items")]
    pub items: Vec<serde_json::Value>,
}

impl DomesticAlarmOutputCollection {
    pub fn new(items: Vec<serde_json::Value>) -> DomesticAlarmOutputCollection {
        DomesticAlarmOutputCollection { items }
    }
}
