/*
 * Somfy Protect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExternalStorageInput {
    /// External video provider name.
    #[serde(rename = "provider")]
    pub provider: String,
    /// Access token.
    #[serde(rename = "accessToken", skip_serializing_if = "Option::is_none")]
    pub access_token: Option<String>,
    /// Refresh token.
    #[serde(rename = "refreshToken", skip_serializing_if = "Option::is_none")]
    pub refresh_token: Option<String>,
}

impl ExternalStorageInput {
    pub fn new(provider: String) -> ExternalStorageInput {
        ExternalStorageInput {
            provider,
            access_token: None,
            refresh_token: None,
        }
    }
}
