/*
 * Somfy Protect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GeoFenceInput {
    /// Latitude.
    #[serde(rename = "latitude", skip_serializing_if = "Option::is_none")]
    pub latitude: Option<f32>,
    /// Longitude.
    #[serde(rename = "longitude", skip_serializing_if = "Option::is_none")]
    pub longitude: Option<f32>,
    /// Radius.
    #[serde(rename = "radius", skip_serializing_if = "Option::is_none")]
    pub radius: Option<f32>,
    /// Trigger exit.
    #[serde(rename = "trigger_exit")]
    pub trigger_exit: bool,
    /// Trigger exit if last.
    #[serde(rename = "trigger_exit_if_last", skip_serializing_if = "Option::is_none")]
    pub trigger_exit_if_last: Option<bool>,
    /// Trigger enter.
    #[serde(rename = "trigger_enter")]
    pub trigger_enter: bool,
    /// Mobile ID used for smart activation and presence. (nullable).
    #[serde(rename = "location_phone_id", skip_serializing_if = "Option::is_none")]
    pub location_phone_id: Option<String>,
}

impl GeoFenceInput {
    pub fn new(trigger_exit: bool, trigger_enter: bool) -> GeoFenceInput {
        GeoFenceInput {
            latitude: None,
            longitude: None,
            radius: None,
            trigger_exit,
            trigger_exit_if_last: None,
            trigger_enter,
            location_phone_id: None,
        }
    }
}


