/*
 * Somfy Protect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Job {
    /// Job identifier.
    #[serde(rename = "job_id")]
    pub job_id: String,
    /// Site identifier.
    #[serde(rename = "site_id")]
    pub site_id: String,
    /// Job owner identifier.
    #[serde(rename = "user_id")]
    pub user_id: String,
    /// Current job state.
    #[serde(rename = "state")]
    pub state: String,
    /// Job creation timestamp in milliseconds.
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<i32>,
}

impl Job {
    pub fn new(job_id: String, site_id: String, user_id: String, state: String) -> Job {
        Job {
            job_id,
            site_id,
            user_id,
            state,
            created_at: None,
        }
    }
}
