/*
 * Somfy Protect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MyfoxAroundOptions {
    /// Myfox Around state.
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<State>,
}

impl MyfoxAroundOptions {
    pub fn new() -> MyfoxAroundOptions {
        MyfoxAroundOptions {
            state: None,
        }
    }
}

/// Myfox Around state.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum State {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
    #[serde(rename = "discovery")]
    Discovery,
}

impl Default for State {
    fn default() -> State {
        Self::Enabled
    }
}

