/*
 * Somfy Protect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct NewPhoto {
    /// The photo encoded with base64.
    #[serde(rename = "base64_raw")]
    pub base64_raw: String,
}

impl NewPhoto {
    pub fn new(base64_raw: String) -> NewPhoto {
        NewPhoto {
            base64_raw,
        }
    }
}


