/*
 * Somfy Protect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Panic {
    /// Type panic mode.
    #[serde(rename = "type")]
    pub r#type: RHashType,
}

impl Panic {
    pub fn new(r#type: RHashType) -> Panic {
        Panic { r#type }
    }
}

/// Type panic mode.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
    #[serde(rename = "silent")]
    Silent,
    #[serde(rename = "alarm")]
    Alarm,
}

impl Default for RHashType {
    fn default() -> RHashType {
        Self::Silent
    }
}
