/*
 * Somfy Protect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Panic {
    /// Type panic mode.
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl Panic {
    pub fn new(r#type: Type) -> Panic {
        Panic { r#type }
    }
}
/// Type panic mode.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "silent")]
    Silent,
    #[serde(rename = "alarm")]
    Alarm,
}

impl Default for Type {
    fn default() -> Type {
        Self::Silent
    }
}
