/*
 * Somfy Protect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlanAvailable {
    /// Code plan by default to show.
    #[serde(rename = "default_code")]
    pub default_code: String,
    /// List of plans.
    #[serde(rename = "items")]
    pub items: Vec<serde_json::Value>,
}

impl PlanAvailable {
    pub fn new(default_code: String, items: Vec<serde_json::Value>) -> PlanAvailable {
        PlanAvailable {
            default_code,
            items,
        }
    }
}
