/*
 * Somfy Protect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PlanCvrCamera {
    /// Price.
    #[serde(rename = "price")]
    pub price: i32,
    /// Camera Name.
    #[serde(rename = "camera_name")]
    pub camera_name: String,
    /// Camera Identifier.
    #[serde(rename = "device_id")]
    pub device_id: String,
    /// Camera has CVR.
    #[serde(rename = "cvr_active")]
    pub cvr_active: bool,
}

impl PlanCvrCamera {
    pub fn new(
        price: i32,
        camera_name: String,
        device_id: String,
        cvr_active: bool,
    ) -> PlanCvrCamera {
        PlanCvrCamera {
            price,
            camera_name,
            device_id,
            cvr_active,
        }
    }
}
