/*
 * Somfy Protect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlanPopup {
    /// Message.
    #[serde(rename = "message")]
    pub message: String,
    /// Text Ok Button.
    #[serde(rename = "btn_ok")]
    pub btn_ok: String,
    /// Text Cancel Button.
    #[serde(rename = "btn_cancel")]
    pub btn_cancel: String,
}

impl PlanPopup {
    pub fn new(message: String, btn_ok: String, btn_cancel: String) -> PlanPopup {
        PlanPopup {
            message,
            btn_ok,
            btn_cancel,
        }
    }
}
