/*
 * Somfy Protect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Reset {
    /// Encrypted reset payload.
    #[serde(rename = "reset", skip_serializing_if = "Option::is_none")]
    pub reset: Option<String>,
}

impl Reset {
    pub fn new() -> Reset {
        Reset { reset: None }
    }
}
