/*
 * Somfy Protect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RoomList {
    /// Room label.
    #[serde(rename = "defaultRoomId", skip_serializing_if = "Option::is_none")]
    pub default_room_id: Option<String>,
    /// Room list.
    #[serde(rename = "rooms")]
    pub rooms: Vec<serde_json::Value>,
}

impl RoomList {
    pub fn new(rooms: Vec<serde_json::Value>) -> RoomList {
        RoomList {
            default_room_id: None,
            rooms,
        }
    }
}


