/*
 * Somfy Protect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ServiceProduct {
    /// Product identifier.
    #[serde(rename = "product_id")]
    pub product_id: ProductId,
}

impl ServiceProduct {
    pub fn new(product_id: ProductId) -> ServiceProduct {
        ServiceProduct { product_id }
    }
}

/// Product identifier.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ProductId {
    #[serde(rename = "cvr1")]
    Cvr1,
    #[serde(rename = "cvr7")]
    Cvr7,
}

impl Default for ProductId {
    fn default() -> ProductId {
        Self::Cvr1
    }
}
