/*
 * Somfy Protect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServiceCheckoutOutput {
    /// Checkout URL.
    #[serde(rename = "location", skip_serializing_if = "Option::is_none")]
    pub location: Option<String>,
    /// Checkout status.
    #[serde(rename = "status")]
    pub status: Status,
}

impl ServiceCheckoutOutput {
    pub fn new(status: Status) -> ServiceCheckoutOutput {
        ServiceCheckoutOutput {
            location: None,
            status,
        }
    }
}
/// Checkout status.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "immediate_new")]
    ImmediateNew,
    #[serde(rename = "immediate_update")]
    ImmediateUpdate,
    #[serde(rename = "postponed_delete")]
    PostponedDelete,
    #[serde(rename = "postponed_update")]
    PostponedUpdate,
}

impl Default for Status {
    fn default() -> Status {
        Self::ImmediateNew
    }
}
