/*
 * Somfy Protect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ServiceInvoiceCollection {
    /// List of invoices.
    #[serde(rename = "items", skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<crate::models::ServiceInvoice>>,
}

impl ServiceInvoiceCollection {
    pub fn new() -> ServiceInvoiceCollection {
        ServiceInvoiceCollection { items: None }
    }
}
