/*
 * Somfy Protect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ServiceSubscription {
    #[serde(rename = "product")]
    pub product: Box<crate::models::ServiceProductOutput>,
    /// Subscription identifier.
    #[serde(rename = "subscription_id", skip_serializing_if = "Option::is_none")]
    pub subscription_id: Option<String>,
    /// Start time of subscription.
    #[serde(rename = "started_at", skip_serializing_if = "Option::is_none")]
    pub started_at: Option<String>,
}

impl ServiceSubscription {
    pub fn new(product: crate::models::ServiceProductOutput) -> ServiceSubscription {
        ServiceSubscription {
            product: Box::new(product),
            subscription_id: None,
            started_at: None,
        }
    }
}
