/*
 * Somfy Protect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServiceSiteServices {
    #[serde(rename = "axa", skip_serializing_if = "Option::is_none")]
    pub axa: Option<Box<models::ServiceSitePartner>>,
    #[serde(rename = "sotel", skip_serializing_if = "Option::is_none")]
    pub sotel: Option<Box<models::ServiceSitePartner>>,
}

impl ServiceSiteServices {
    pub fn new() -> ServiceSiteServices {
        ServiceSiteServices {
            axa: None,
            sotel: None,
        }
    }
}
