/*
 * Somfy Protect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ServiceSitePartner {
    /// Site partner name.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Site partner status.
    #[serde(rename = "status")]
    pub status: Status,
    /// Specific data for this partner.
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<String>>,
}

impl ServiceSitePartner {
    pub fn new(status: Status) -> ServiceSitePartner {
        ServiceSitePartner {
            name: None,
            status,
            data: None,
        }
    }
}

/// Site partner status.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
    #[serde(rename = "deleted")]
    Deleted,
    #[serde(rename = "incomplete")]
    Incomplete,
    #[serde(rename = "error")]
    Error,
    #[serde(rename = "waiting")]
    Waiting,
}

impl Default for Status {
    fn default() -> Status {
        Self::Enabled
    }
}
