/*
 * Somfy Protect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SiteInstallerAddRequest {
    /// Error user not found
    #[serde(rename = "user_email", skip_serializing_if = "Option::is_none")]
    pub user_email: Option<String>,
}

impl SiteInstallerAddRequest {
    pub fn new() -> SiteInstallerAddRequest {
        SiteInstallerAddRequest { user_email: None }
    }
}
