/*
 * Somfy Protect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SiteDiagnosis {
    #[serde(rename = "main_status", skip_serializing_if = "Option::is_none")]
    pub main_status: Option<MainStatus>,
    #[serde(rename = "main_message", skip_serializing_if = "Option::is_none")]
    pub main_message: Option<String>,
    #[serde(rename = "main_message_vars", skip_serializing_if = "Option::is_none")]
    pub main_message_vars: Option<std::collections::HashMap<String, String>>,
    #[serde(
        rename = "device_diagnosis_available",
        skip_serializing_if = "Option::is_none"
    )]
    pub device_diagnosis_available: Option<bool>,
    #[serde(
        rename = "device_diagnosis_expired",
        skip_serializing_if = "Option::is_none"
    )]
    pub device_diagnosis_expired: Option<bool>,
    #[serde(rename = "items", skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<models::SiteDiagnosisItem>>,
}

impl SiteDiagnosis {
    pub fn new() -> SiteDiagnosis {
        SiteDiagnosis {
            main_status: None,
            main_message: None,
            main_message_vars: None,
            device_diagnosis_available: None,
            device_diagnosis_expired: None,
            items: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MainStatus {
    #[serde(rename = "ok")]
    Ok,
    #[serde(rename = "device-offline")]
    DeviceOffline,
    #[serde(rename = "device-warning")]
    DeviceWarning,
}

impl Default for MainStatus {
    fn default() -> MainStatus {
        Self::Ok
    }
}
