/*
 * Somfy Protect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SitePrivacy {
    /// New state.
    #[serde(rename = "state")]
    pub state: State,
}

impl SitePrivacy {
    pub fn new(state: State) -> SitePrivacy {
        SitePrivacy { state }
    }
}
/// New state.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum State {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "inactive")]
    Inactive,
}

impl Default for State {
    fn default() -> State {
        Self::Active
    }
}
