/*
 * Somfy Protect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SiteCollection {
    /// Output[] List of sites.
    #[serde(rename = "items")]
    pub items: Vec<models::SiteOutput>,
    /// The default site identifier.
    #[serde(rename = "default", skip_serializing_if = "Option::is_none")]
    pub default: Option<String>,
}

impl SiteCollection {
    pub fn new(items: Vec<models::SiteOutput>) -> SiteCollection {
        SiteCollection {
            items,
            default: None,
        }
    }
}
