/*
 * Somfy Protect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SitePaymentMethodUpdateOutput {
    /// Checkout URL.
    #[serde(rename = "location", skip_serializing_if = "Option::is_none")]
    pub location: Option<String>,
}

impl SitePaymentMethodUpdateOutput {
    pub fn new() -> SitePaymentMethodUpdateOutput {
        SitePaymentMethodUpdateOutput { location: None }
    }
}
