/*
 * Somfy Protect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SiteServicesOutput {
    /// Backup sms status.
    #[serde(rename = "backup_sms", skip_serializing_if = "Option::is_none")]
    pub backup_sms: Option<bool>,
    /// SomfyAround service status.
    #[serde(
        rename = "mfa_service_enabled",
        skip_serializing_if = "Option::is_none"
    )]
    pub mfa_service_enabled: Option<bool>,
    /// LoraWan service status.
    #[serde(rename = "lora_enabled", skip_serializing_if = "Option::is_none")]
    pub lora_enabled: Option<bool>,
    /// Monitoring service status.
    #[serde(rename = "monitoring_enabled", skip_serializing_if = "Option::is_none")]
    pub monitoring_enabled: Option<bool>,
    /// Intervention service status.
    #[serde(
        rename = "on_site_intervention_enabled",
        skip_serializing_if = "Option::is_none"
    )]
    pub on_site_intervention_enabled: Option<bool>,
    /// Link connection over gsm service status.
    #[serde(
        rename = "link_over_gsm_enabled",
        skip_serializing_if = "Option::is_none"
    )]
    pub link_over_gsm_enabled: Option<bool>,
}

impl SiteServicesOutput {
    pub fn new() -> SiteServicesOutput {
        SiteServicesOutput {
            backup_sms: None,
            mfa_service_enabled: None,
            lora_enabled: None,
            monitoring_enabled: None,
            on_site_intervention_enabled: None,
            link_over_gsm_enabled: None,
        }
    }
}
