/*
 * Somfy Protect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserSiteProfile {
    /// Type of profile.
    #[serde(rename = "type")]
    pub r#type: Type,
    /// Profile enabled?
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
}

impl UserSiteProfile {
    pub fn new(r#type: Type) -> UserSiteProfile {
        UserSiteProfile {
            r#type,
            enabled: None,
        }
    }
}
/// Type of profile.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "admin")]
    Admin,
    #[serde(rename = "owner")]
    Owner,
    #[serde(rename = "guest")]
    Guest,
    #[serde(rename = "kid")]
    Kid,
    #[serde(rename = "family")]
    Family,
    #[serde(rename = "neighbor")]
    Neighbor,
    #[serde(rename = "custom")]
    Custom,
}

impl Default for Type {
    fn default() -> Type {
        Self::Admin
    }
}
