/*
 * Somfy Protect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserGuestAbstract {
    /// Site identifier.
    #[serde(rename = "site_id")]
    pub site_id: String,
    /// User display name on the site.
    #[serde(rename = "display_name")]
    pub display_name: String,
    /// Identifier of user photo.
    #[serde(rename = "photo_id", skip_serializing_if = "Option::is_none")]
    pub photo_id: Option<String>,
    /// User firstname.
    #[serde(rename = "firstname", skip_serializing_if = "Option::is_none")]
    pub firstname: Option<String>,
    /// User lastname.
    #[serde(rename = "lastname", skip_serializing_if = "Option::is_none")]
    pub lastname: Option<String>,
    /// Profiles of user for this site.
    #[serde(rename = "profiles", skip_serializing_if = "Option::is_none")]
    pub profiles: Option<Vec<models::UserSiteProfile>>,
}

impl UserGuestAbstract {
    pub fn new(site_id: String, display_name: String) -> UserGuestAbstract {
        UserGuestAbstract {
            site_id,
            display_name,
            photo_id: None,
            firstname: None,
            lastname: None,
            profiles: None,
        }
    }
}
