/*
 * Somfy Protect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UserSiteAction {
    /// Action type.
    #[serde(rename = "action")]
    pub action: Action,
    #[serde(rename = "params", skip_serializing_if = "Option::is_none")]
    pub params: Option<Box<crate::models::UserSiteActionParameters>>,
}

impl UserSiteAction {
    pub fn new(action: Action) -> UserSiteAction {
        UserSiteAction {
            action,
            params: None,
        }
    }
}

/// Action type.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Action {
    #[serde(rename = "checkin")]
    Checkin,
    #[serde(rename = "checkout")]
    Checkout,
    #[serde(rename = "fromtoken")]
    Fromtoken,
    #[serde(rename = "alexaSelect")]
    AlexaSelect,
}

impl Default for Action {
    fn default() -> Action {
        Self::Checkin
    }
}
