/*
 * Somfy Protect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserCollection {
    /// List of users.
    #[serde(rename = "items")]
    pub items: Vec<models::UserOutputForSite>,
}

impl UserCollection {
    pub fn new(items: Vec<models::UserOutputForSite>) -> UserCollection {
        UserCollection { items }
    }
}
