/*
 * Somfy Protect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WifiCredentials {
    /// Wifi SSID.
    #[serde(rename = "wifi_s_s_i_d", skip_serializing_if = "Option::is_none")]
    pub wifi_s_s_i_d: Option<String>,
    /// Wifi Password.
    #[serde(rename = "wifi_password", skip_serializing_if = "Option::is_none")]
    pub wifi_password: Option<String>,
}

impl WifiCredentials {
    pub fn new() -> WifiCredentials {
        WifiCredentials {
            wifi_s_s_i_d: None,
            wifi_password: None,
        }
    }
}
