/*
 * Somfy Protect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use reqwest;

use super::{configuration, Error};
use crate::apis::ResponseContent;

/// struct for passing parameters to the method [`site_calendar_scenario_create`]
#[derive(Clone, Debug, Default)]
pub struct SiteCalendarScenarioCreateParams {
    /// Site identifier
    pub site_id: String,
}

/// struct for passing parameters to the method [`site_calendar_scenario_delete`]
#[derive(Clone, Debug, Default)]
pub struct SiteCalendarScenarioDeleteParams {
    /// Site identifier
    pub site_id: String,
    /// Calendar scenario id
    pub scenario_id: String,
}

/// struct for passing parameters to the method [`site_calendar_scenario_get`]
#[derive(Clone, Debug, Default)]
pub struct SiteCalendarScenarioGetParams {
    /// Site identifier
    pub site_id: String,
    /// Calendar scenario id
    pub scenario_id: String,
}

/// struct for passing parameters to the method [`site_calendar_scenario_get_list`]
#[derive(Clone, Debug, Default)]
pub struct SiteCalendarScenarioGetListParams {
    /// Site identifier
    pub site_id: String,
}

/// struct for passing parameters to the method [`site_calendar_scenario_update`]
#[derive(Clone, Debug, Default)]
pub struct SiteCalendarScenarioUpdateParams {
    /// Site identifier
    pub site_id: String,
    /// Calendar scenario id
    pub scenario_id: String,
}

/// struct for typed errors of method [`site_calendar_scenario_create`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SiteCalendarScenarioCreateError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`site_calendar_scenario_delete`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SiteCalendarScenarioDeleteError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`site_calendar_scenario_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SiteCalendarScenarioGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`site_calendar_scenario_get_list`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SiteCalendarScenarioGetListError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`site_calendar_scenario_update`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SiteCalendarScenarioUpdateError {
    UnknownValue(serde_json::Value),
}

pub async fn site_calendar_scenario_create(
    configuration: &configuration::Configuration,
    params: SiteCalendarScenarioCreateParams,
) -> Result<(), Error<SiteCalendarScenarioCreateError>> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let site_id = params.site_id;

    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!(
        "{}/site/{site_id}/scenario-calendar",
        local_var_configuration.base_path,
        site_id = crate::apis::urlencode(site_id)
    );
    let mut local_var_req_builder =
        local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder =
            local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        Ok(())
    } else {
        let local_var_entity: Option<SiteCalendarScenarioCreateError> =
            serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent {
            status: local_var_status,
            content: local_var_content,
            entity: local_var_entity,
        };
        Err(Error::ResponseError(local_var_error))
    }
}

pub async fn site_calendar_scenario_delete(
    configuration: &configuration::Configuration,
    params: SiteCalendarScenarioDeleteParams,
) -> Result<(), Error<SiteCalendarScenarioDeleteError>> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let site_id = params.site_id;
    let scenario_id = params.scenario_id;

    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!(
        "{}/site/{site_id}/scenario-calendar/{scenario_id}",
        local_var_configuration.base_path,
        site_id = crate::apis::urlencode(site_id),
        scenario_id = crate::apis::urlencode(scenario_id)
    );
    let mut local_var_req_builder =
        local_var_client.request(reqwest::Method::DELETE, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder =
            local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        Ok(())
    } else {
        let local_var_entity: Option<SiteCalendarScenarioDeleteError> =
            serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent {
            status: local_var_status,
            content: local_var_content,
            entity: local_var_entity,
        };
        Err(Error::ResponseError(local_var_error))
    }
}

pub async fn site_calendar_scenario_get(
    configuration: &configuration::Configuration,
    params: SiteCalendarScenarioGetParams,
) -> Result<(), Error<SiteCalendarScenarioGetError>> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let site_id = params.site_id;
    let scenario_id = params.scenario_id;

    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!(
        "{}/site/{site_id}/scenario-calendar/{scenario_id}",
        local_var_configuration.base_path,
        site_id = crate::apis::urlencode(site_id),
        scenario_id = crate::apis::urlencode(scenario_id)
    );
    let mut local_var_req_builder =
        local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder =
            local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        Ok(())
    } else {
        let local_var_entity: Option<SiteCalendarScenarioGetError> =
            serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent {
            status: local_var_status,
            content: local_var_content,
            entity: local_var_entity,
        };
        Err(Error::ResponseError(local_var_error))
    }
}

pub async fn site_calendar_scenario_get_list(
    configuration: &configuration::Configuration,
    params: SiteCalendarScenarioGetListParams,
) -> Result<(), Error<SiteCalendarScenarioGetListError>> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let site_id = params.site_id;

    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!(
        "{}/site/{site_id}/scenario-calendar",
        local_var_configuration.base_path,
        site_id = crate::apis::urlencode(site_id)
    );
    let mut local_var_req_builder =
        local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder =
            local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        Ok(())
    } else {
        let local_var_entity: Option<SiteCalendarScenarioGetListError> =
            serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent {
            status: local_var_status,
            content: local_var_content,
            entity: local_var_entity,
        };
        Err(Error::ResponseError(local_var_error))
    }
}

pub async fn site_calendar_scenario_update(
    configuration: &configuration::Configuration,
    params: SiteCalendarScenarioUpdateParams,
) -> Result<(), Error<SiteCalendarScenarioUpdateError>> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let site_id = params.site_id;
    let scenario_id = params.scenario_id;

    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!(
        "{}/site/{site_id}/scenario-calendar/{scenario_id}",
        local_var_configuration.base_path,
        site_id = crate::apis::urlencode(site_id),
        scenario_id = crate::apis::urlencode(scenario_id)
    );
    let mut local_var_req_builder =
        local_var_client.request(reqwest::Method::PUT, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder =
            local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        Ok(())
    } else {
        let local_var_entity: Option<SiteCalendarScenarioUpdateError> =
            serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent {
            status: local_var_status,
            content: local_var_content,
            entity: local_var_entity,
        };
        Err(Error::ResponseError(local_var_error))
    }
}
