/*
 * Somfy Protect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{Deserialize, Serialize};

/// struct for passing parameters to the method [`get_photo`]
#[derive(Clone, Debug)]
pub struct GetPhotoParams {
    /// Photo identifier
    pub photo_id: String,
}

/// struct for passing parameters to the method [`upload_photo`]
#[derive(Clone, Debug)]
pub struct UploadPhotoParams {
    /// Photo to upload
    pub photo: models::NewPhoto,
}

/// struct for typed errors of method [`get_photo`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetPhotoError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`upload_photo`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UploadPhotoError {
    UnknownValue(serde_json::Value),
}

pub async fn get_photo(
    configuration: &configuration::Configuration,
    params: GetPhotoParams,
) -> Result<(), Error<GetPhotoError>> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let photo_id = params.photo_id;

    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!(
        "{}/photo/{photo_id}",
        local_var_configuration.base_path,
        photo_id = crate::apis::urlencode(photo_id)
    );
    let mut local_var_req_builder =
        local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder =
            local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        Ok(())
    } else {
        let local_var_entity: Option<GetPhotoError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent {
            status: local_var_status,
            content: local_var_content,
            entity: local_var_entity,
        };
        Err(Error::ResponseError(local_var_error))
    }
}

pub async fn upload_photo(
    configuration: &configuration::Configuration,
    params: UploadPhotoParams,
) -> Result<models::UploadedPhoto, Error<UploadPhotoError>> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let photo = params.photo;

    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/photo", local_var_configuration.base_path);
    let mut local_var_req_builder =
        local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder =
            local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };
    local_var_req_builder = local_var_req_builder.json(&photo);

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<UploadPhotoError> =
            serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent {
            status: local_var_status,
            content: local_var_content,
            entity: local_var_entity,
        };
        Err(Error::ResponseError(local_var_error))
    }
}
