/*
 * Somfy Protect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LoraWanCover {
    /// Result of cover test.
    #[serde(rename = "lora_wan_cover_test_result")]
    pub lora_wan_cover_test_result: bool,
}

impl LoraWanCover {
    pub fn new(lora_wan_cover_test_result: bool) -> LoraWanCover {
        LoraWanCover {
            lora_wan_cover_test_result,
        }
    }
}


