/*
 * Somfy Protect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PlanFeature {
    /// Text.
    #[serde(rename = "text")]
    pub text: String,
    /// Style.
    #[serde(rename = "style", skip_serializing_if = "Option::is_none")]
    pub style: Option<String>,
    /// Group.
    #[serde(rename = "group", skip_serializing_if = "Option::is_none")]
    pub group: Option<i32>,
}

impl PlanFeature {
    pub fn new(text: String) -> PlanFeature {
        PlanFeature {
            text,
            style: None,
            group: None,
        }
    }
}


