/*
 * Somfy Protect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PlanPrice {
    /// Period.
    #[serde(rename = "period")]
    pub period: String,
    /// Price.
    #[serde(rename = "price")]
    pub price: i32,
}

impl PlanPrice {
    pub fn new(period: String, price: i32) -> PlanPrice {
        PlanPrice {
            period,
            price,
        }
    }
}


