/*
 * Somfy Protect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SiteInvitationAnswer {
    /// Answer for invitation.
    #[serde(rename = "answer")]
    pub answer: Answer,
}

impl SiteInvitationAnswer {
    pub fn new(answer: Answer) -> SiteInvitationAnswer {
        SiteInvitationAnswer {
            answer,
        }
    }
}

/// Answer for invitation.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Answer {
    #[serde(rename = "accept")]
    Accept,
    #[serde(rename = "decline")]
    Decline,
}

impl Default for Answer {
    fn default() -> Answer {
        Self::Accept
    }
}

